### ISSUE TITLE
Problem when trying to log in with OAuth

### ISSUE THREAD

**Issue by Galaniberico** [mauritzn/Web-Viewer-KDE-Widget#2]
I was trying to use the widget, but when I try to log in into a page with Google option, it do not open any Google's login page and just nothing happens. May it be because the widget do not connect correctly with an external navigator to log in or something like that?

Thanks in advance ^^

**Comment by mauritzn** [comment]
This widget is exceptionally simple and uses the default QT Webview to handle webpage rendering, as such I'm guessing the webpage you are trying access shows the Google login page as a popup which doesn't get handled by QT's Webview by default. Honestly I have no idea how QT handles login sessions in general _(e.g. where session cookies are stored nor how they are stored)_ and would probably refrain from using it that way.

I haven't made use of this widget nor KDE for a few years so I can't really say this widget is battle tested. I only intended for it to be used for simple public information and never tried it with login sessions.

It might be possible to intercept the popup window and somehow handle it correctly, QT provides a signal for new window requests called [`newViewRequested`](https://doc.qt.io/Qt-5/qml-qtwebengine-webengineview.html#newViewRequested-signal) using that signal it might be possible to handle the login correctly, but I'm not 100% sure how you'd implement that in a widget where you cannot freely create windows on the screen. Sending the login request to the main browser would be preferable but I'm not sure how you would send the finished request back to the widget.

A possible simple bypass might be opening it in another browser and copy the URL of the Google login page then use that as the URL for the widget and then change it back to the correct page after the login is complete, but I haven't tested that.

I honestly thought I had archived this repo already, but seems I forgot to do that, the main reason is that I no longer use this widget and as such cannot really maintain it.

Sorry that I cannot be more helpful. I'll leave this repo open for another week if you'd like to reply and maybe brainstorm some solutions, but after that I'll be adding a note to the README _(and archiving it)_ that this repo is no longer maintained and should probably be avoided.
